### ISSUE TITLE
Right Now the project Roadmap

### ISSUE THREAD

**Issue by ChenYujunjks** [ChenYujunjks/flight_management_sys#5]
# 🛤️ Project Roadmap: Flight Management System

以下是针对 Flight Management System 项目当前需要完成的任务和未来规划的开发计划：

---

### 1. 将 ShadCN UI 的 `Calendar` 和 `Date Picker` 组件集成到项目中
- [ ] 集成 ShadCN UI 的 `Calendar` 组件：
  - [参考文档链接](https://ui.shadcn.com/docs/components/calendar)
- [ ] 集成 ShadCN UI 的 `Date Picker` 组件：
  - [参考文档链接](https://ui.shadcn.com/docs/components/date-picker)

### 2. 完成后端逻辑服务：`Flight` 和 `Ticket` 路由
- [ ] 开发 `Flight` 路由：
  - 增加航班管理功能，包括增删改查接口。
- [ ] 开发 `Ticket` 路由：
  - 实现机票预订和查询的后端逻辑服务。
  
### 3. 完成 `(auth)/sign-in` 路由
- [ ] 创建并完善 `(auth)/sign-in` 路由：
  - 集成用户登录表单。
  - 与后端 `auth` 服务对接完成。

---

### 4. 进行模块化处理前端代码
- [ ] 在 `components` 文件夹下创建以下子模块：
  - `/auth`：用户登录和注册组件。
  - `/flight`：航班相关组件。
  - `/ticket`：机票预订相关组件。

### 5. 界面优化与核心功能开发
- [ ] 优化前端界面，提升用户体验。
- [ ] 实现航班管理功能的前端模块：
  - 航班信息展示。
  - 航班状态更新。
- [ ] 实现机票预订功能的前端模块：
  - 用户选择航班并预订。
  - 生成并展示机票信息。

### 6. 添加单元测试与集成测试
- [ ] 编写单元测试，覆盖关键后端逻辑。
- [ ] 实现前后端的集成测试，确保系统功能正常运行。

### 7. 部署与文档整理
- [ ] 部署项目到生产环境。
- [ ] 编写和完善项目文档：
  - 开发者指南。
  - API 文档。

---

## 🔵 长期规划
- [ ] 增加数据可视化模块：
  - 航班和票务数据的统计与分析。
- [ ] 支持多语言功能，提升用户覆盖面。
- [ ] 集成支付网关，完善支付功能。

---

💡 **更新说明**：
该 Roadmap 会根据项目需求和开发进度进行定期更新。
